export const ErrorCodes = {
  WORK_DUPLICATE_UBQN: 'WORK_DUPLICATE_UBQN',
  WORK_NOT_FOUND: 'WORK_NOT_FOUND',
  QUOTATION_EXISTS: 'QUOTATION_EXISTS',
  QUOTATION_REQUIRED: 'QUOTATION_REQUIRED',
  FORWARDING_REQUIRED: 'FORWARDING_REQUIRED',
  LINKED_RECORDS_EXIST: 'LINKED_RECORDS_EXIST',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SESSION_EXPIRED: 'SESSION_EXPIRED'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
