// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Fail fast with a clear error instead of hanging during auth bootstrapping.
  // Avoid logging the full key; just indicate presence/length.
  console.error('Missing Supabase env vars', {
    hasUrl: Boolean(SUPABASE_URL),
    keyLength: SUPABASE_PUBLISHABLE_KEY?.length ?? 0,
  });
  throw new Error('Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY');
}

if (import.meta.env.DEV) {
  // Helpful dev-time signal that envs are loaded without leaking the key.
  console.info('Supabase env loaded', {
    url: SUPABASE_URL,
    keyPrefix: SUPABASE_PUBLISHABLE_KEY.slice(0, 12),
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storage = (() => {
  try {
    const s = localStorage;
    const testKey = '__supabase_storage_test__';
    s.setItem(testKey, '1');
    s.removeItem(testKey);
    return s;
  } catch {
    console.warn('localStorage unavailable, falling back to in-memory auth');
    return undefined;
  }
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: Boolean(storage),
    autoRefreshToken: true,
  }
});
